FROM disconnect3d/gdb-py2-and-py3

# Set the locales required by pwndbg
RUN apt-get update && apt-get install -y locales
RUN sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen && \
    locale-gen
ENV LANG en_US.UTF-8  
ENV LANGUAGE en_US:en  
ENV LC_ALL en_US.UTF-8     


RUN git clone https://github.com/pwndbg/pwndbg.git && cd pwndbg && ./setup.sh
